spring.application.name=user-service
server.port=8082

spring.datasource.url=jdbc:postgresql://postgresql:5432/is_user
#spring.datasource.url=jdbc:postgresql://localhost:5432/is_user
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8181}/realms/cloud-realm
#spring.security.oauth2.resourceserver.jwt.issuer-uri: http://34.116.235.108/realms/cloud-realm
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://34.116.235.108/realms/garment_print

keycloak.server-url=https://34.116.235.108
keycloak.realm=garment_print
keycloak.client-id=order-processing
keycloak.username=${KEYCLOAK_USERNAME}
keycloak.password=${KEYCLOAK_PASSWORD}
keycloak.target-client-id=order-processing

#spring.cloud.consul.host=localhost
#spring.cloud.consul.port=8500
#spring.cloud.consul.discovery.enabled=true
#spring.cloud.consul.discovery.register=true
#spring.cloud.consul.discovery.service-name=${spring.application.name}

#frontend-url=http://localhost:3000
frontend-url=http://frontend:80

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always